[tool.ruff]
target-version = "py311"
include = ["*.py"]
exclude = ["src/alembic/versions/*.py"]
line-length = 119

[tool.ruff.lint]
select = [
  "C90",
  "D",
  "E",
  "F",
  "I",
  "W",
]
ignore = [
  "D100",
  "E501",
  "D400",
  "D415",
]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["musubi_restapi"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
split-on-trailing-comma = true